/* Generated by Yosys 0.51+46 (git sha1 8bde6ac17, g++ 11.4.0-1ubuntu1~22.04 -fPIC -O3) */

module I2C_Master(start, Data, clk, rst, SCL_I, SDA_I, SCL_O, SDA_O, received_data);
  wire _000_;
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire [2:0] _070_;
  wire [7:0] _071_;
  wire [7:0] _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  wire [2:0] _078_;
  wire _079_;
  wire _080_;
  input [7:0] Data;
  wire [7:0] Data;
  input SCL_I;
  wire SCL_I;
  output SCL_O;
  wire SCL_O;
  input SDA_I;
  wire SDA_I;
  output SDA_O;
  wire SDA_O;
  wire V_SCL;
  wire begin_rec;
  input clk;
  wire clk;
  wire [2:0] counter;
  wire [2:0] cs;
  wire done_receiving;
  wire [2:0] ns;
  wire receive;
  output [7:0] received_data;
  wire [7:0] received_data;
  input rst;
  wire rst;
  input start;
  wire start;
  wire writing;
  sky130_fd_sc_hd__clkinv_1 _081_ (
    .A(counter[0]),
    .Y(_036_)
  );
  sky130_fd_sc_hd__clkinv_1 _082_ (
    .A(cs[1]),
    .Y(_037_)
  );
  sky130_fd_sc_hd__clkinv_1 _083_ (
    .A(SCL_I),
    .Y(_038_)
  );
  sky130_fd_sc_hd__clkinv_1 _084_ (
    .A(done_receiving),
    .Y(_039_)
  );
  sky130_fd_sc_hd__nor2_1 _085_ (
    .A(counter[0]),
    .B(counter[1]),
    .Y(_040_)
  );
  sky130_fd_sc_hd__and3b_1 _086_ (
    .A_N(cs[1]),
    .B(cs[2]),
    .C(cs[0]),
    .X(_041_)
  );
  sky130_fd_sc_hd__nand4b_1 _087_ (
    .A_N(cs[1]),
    .B(cs[2]),
    .C(begin_rec),
    .D(cs[0]),
    .Y(_042_)
  );
  sky130_fd_sc_hd__nand3_1 _088_ (
    .A(begin_rec),
    .B(_040_),
    .C(_041_),
    .Y(_043_)
  );
  sky130_fd_sc_hd__nor2_1 _089_ (
    .A(V_SCL),
    .B(_042_),
    .Y(_044_)
  );
  sky130_fd_sc_hd__lpflow_inputiso1p_1 _090_ (
    .A(V_SCL),
    .SLEEP(_042_),
    .X(_045_)
  );
  sky130_fd_sc_hd__nor3_1 _091_ (
    .A(counter[2]),
    .B(V_SCL),
    .C(_043_),
    .Y(_046_)
  );
  sky130_fd_sc_hd__mux2_1 _092_ (
    .A0(received_data[0]),
    .A1(SDA_I),
    .S(_046_),
    .X(_072_[0])
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _093_ (
    .A(counter[0]),
    .SLEEP(counter[1]),
    .X(_047_)
  );
  sky130_fd_sc_hd__o41ai_1 _094_ (
    .A1(_036_),
    .A2(counter[2]),
    .A3(counter[1]),
    .A4(_045_),
    .B1(received_data[1]),
    .Y(_048_)
  );
  sky130_fd_sc_hd__nand2_1 _095_ (
    .A(SDA_I),
    .B(_047_),
    .Y(_049_)
  );
  sky130_fd_sc_hd__xnor2_1 _096_ (
    .A(counter[2]),
    .B(_040_),
    .Y(_050_)
  );
  sky130_fd_sc_hd__nand2_1 _097_ (
    .A(_044_),
    .B(_050_),
    .Y(_051_)
  );
  sky130_fd_sc_hd__o21ai_0 _098_ (
    .A1(_049_),
    .A2(_051_),
    .B1(_048_),
    .Y(_072_[1])
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _099_ (
    .A(counter[1]),
    .SLEEP(counter[0]),
    .X(_052_)
  );
  sky130_fd_sc_hd__nand3_1 _100_ (
    .A(_044_),
    .B(_050_),
    .C(_052_),
    .Y(_053_)
  );
  sky130_fd_sc_hd__nand2_1 _101_ (
    .A(SDA_I),
    .B(_052_),
    .Y(_054_)
  );
  sky130_fd_sc_hd__o2bb2ai_1 _102_ (
    .A1_N(received_data[2]),
    .A2_N(_053_),
    .B1(_054_),
    .B2(_051_),
    .Y(_072_[2])
  );
  sky130_fd_sc_hd__nand4_1 _103_ (
    .A(counter[0]),
    .B(counter[1]),
    .C(_044_),
    .D(_050_),
    .Y(_055_)
  );
  sky130_fd_sc_hd__mux2_1 _104_ (
    .A0(SDA_I),
    .A1(received_data[3]),
    .S(_055_),
    .X(_072_[3])
  );
  sky130_fd_sc_hd__nand3_1 _105_ (
    .A(counter[2]),
    .B(_040_),
    .C(_044_),
    .Y(_056_)
  );
  sky130_fd_sc_hd__mux2_1 _106_ (
    .A0(SDA_I),
    .A1(received_data[4]),
    .S(_056_),
    .X(_072_[4])
  );
  sky130_fd_sc_hd__nand3_1 _107_ (
    .A(counter[2]),
    .B(_044_),
    .C(_047_),
    .Y(_057_)
  );
  sky130_fd_sc_hd__nor3_1 _108_ (
    .A(_045_),
    .B(_049_),
    .C(_050_),
    .Y(_058_)
  );
  sky130_fd_sc_hd__a21o_1 _109_ (
    .A1(received_data[5]),
    .A2(_057_),
    .B1(_058_),
    .X(_072_[5])
  );
  sky130_fd_sc_hd__nand4_1 _110_ (
    .A(_036_),
    .B(counter[2]),
    .C(counter[1]),
    .D(_044_),
    .Y(_059_)
  );
  sky130_fd_sc_hd__nor3_1 _111_ (
    .A(_045_),
    .B(_050_),
    .C(_054_),
    .Y(_060_)
  );
  sky130_fd_sc_hd__a21o_1 _112_ (
    .A1(received_data[6]),
    .A2(_059_),
    .B1(_060_),
    .X(_072_[6])
  );
  sky130_fd_sc_hd__nand4_1 _113_ (
    .A(counter[0]),
    .B(counter[2]),
    .C(counter[1]),
    .D(_044_),
    .Y(_061_)
  );
  sky130_fd_sc_hd__mux2_1 _114_ (
    .A0(SDA_I),
    .A1(received_data[7]),
    .S(_061_),
    .X(_072_[7])
  );
  sky130_fd_sc_hd__lpflow_inputiso1p_1 _115_ (
    .A(cs[0]),
    .SLEEP(cs[1]),
    .X(_062_)
  );
  sky130_fd_sc_hd__nor2_1 _116_ (
    .A(cs[2]),
    .B(_062_),
    .Y(_063_)
  );
  sky130_fd_sc_hd__or3_1 _117_ (
    .A(cs[0]),
    .B(cs[1]),
    .C(cs[2]),
    .X(_064_)
  );
  sky130_fd_sc_hd__nor3_1 _118_ (
    .A(cs[0]),
    .B(cs[2]),
    .C(Data[0]),
    .Y(_065_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _119_ (
    .A(Data[0]),
    .SLEEP(writing),
    .X(_066_)
  );
  sky130_fd_sc_hd__nand2b_1 _120_ (
    .A_N(writing),
    .B(Data[0]),
    .Y(_067_)
  );
  sky130_fd_sc_hd__nor2_1 _121_ (
    .A(writing),
    .B(_065_),
    .Y(_068_)
  );
  sky130_fd_sc_hd__nor2_1 _122_ (
    .A(_063_),
    .B(_068_),
    .Y(_073_)
  );
  sky130_fd_sc_hd__a31oi_1 _123_ (
    .A1(SDA_I),
    .A2(_038_),
    .A3(_041_),
    .B1(begin_rec),
    .Y(_069_)
  );
  sky130_fd_sc_hd__nor2_1 _124_ (
    .A(_063_),
    .B(_069_),
    .Y(_074_)
  );
  sky130_fd_sc_hd__o22ai_1 _125_ (
    .A1(counter[2]),
    .A2(_043_),
    .B1(_063_),
    .B2(_039_),
    .Y(_075_)
  );
  sky130_fd_sc_hd__a21o_1 _126_ (
    .A1(receive),
    .A2(_064_),
    .B1(_041_),
    .X(_076_)
  );
  sky130_fd_sc_hd__nor3b_1 _127_ (
    .A(cs[0]),
    .B(cs[2]),
    .C_N(cs[1]),
    .Y(_000_)
  );
  sky130_fd_sc_hd__or3b_1 _128_ (
    .A(cs[0]),
    .B(cs[2]),
    .C_N(cs[1]),
    .X(_001_)
  );
  sky130_fd_sc_hd__nor2_1 _129_ (
    .A(_041_),
    .B(_000_),
    .Y(_002_)
  );
  sky130_fd_sc_hd__a21oi_1 _130_ (
    .A1(V_SCL),
    .A2(_002_),
    .B1(_063_),
    .Y(_003_)
  );
  sky130_fd_sc_hd__o21ai_0 _131_ (
    .A1(SCL_O),
    .A2(_002_),
    .B1(_003_),
    .Y(_077_)
  );
  sky130_fd_sc_hd__nand2_1 _132_ (
    .A(cs[0]),
    .B(cs[1]),
    .Y(_004_)
  );
  sky130_fd_sc_hd__clkinv_1 _133_ (
    .A(_004_),
    .Y(_005_)
  );
  sky130_fd_sc_hd__a21oi_1 _134_ (
    .A1(cs[0]),
    .A2(_037_),
    .B1(cs[2]),
    .Y(_006_)
  );
  sky130_fd_sc_hd__a21oi_1 _135_ (
    .A1(_062_),
    .A2(_004_),
    .B1(cs[2]),
    .Y(_007_)
  );
  sky130_fd_sc_hd__a21o_1 _136_ (
    .A1(_042_),
    .A2(_001_),
    .B1(V_SCL),
    .X(_008_)
  );
  sky130_fd_sc_hd__xnor2_1 _137_ (
    .A(counter[0]),
    .B(_008_),
    .Y(_009_)
  );
  sky130_fd_sc_hd__lpflow_inputiso1p_1 _138_ (
    .A(_007_),
    .SLEEP(_009_),
    .X(_078_[0])
  );
  sky130_fd_sc_hd__a21oi_1 _139_ (
    .A1(counter[1]),
    .A2(_008_),
    .B1(_007_),
    .Y(_010_)
  );
  sky130_fd_sc_hd__o31ai_1 _140_ (
    .A1(_047_),
    .A2(_052_),
    .A3(_008_),
    .B1(_010_),
    .Y(_078_[1])
  );
  sky130_fd_sc_hd__a21oi_1 _141_ (
    .A1(counter[2]),
    .A2(_008_),
    .B1(_007_),
    .Y(_011_)
  );
  sky130_fd_sc_hd__o21ai_0 _142_ (
    .A1(_050_),
    .A2(_008_),
    .B1(_011_),
    .Y(_078_[2])
  );
  sky130_fd_sc_hd__mux4_2 _143_ (
    .A0(Data[0]),
    .A1(Data[1]),
    .A2(Data[2]),
    .A3(Data[3]),
    .S0(counter[0]),
    .S1(counter[1]),
    .X(_012_)
  );
  sky130_fd_sc_hd__nor2b_1 _144_ (
    .A(counter[2]),
    .B_N(_012_),
    .Y(_013_)
  );
  sky130_fd_sc_hd__mux4_2 _145_ (
    .A0(Data[4]),
    .A1(Data[5]),
    .A2(Data[6]),
    .A3(Data[7]),
    .S0(counter[0]),
    .S1(counter[1]),
    .X(_014_)
  );
  sky130_fd_sc_hd__a211oi_1 _146_ (
    .A1(counter[2]),
    .A2(_014_),
    .B1(_013_),
    .C1(V_SCL),
    .Y(_015_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _147_ (
    .A(V_SCL),
    .SLEEP(SDA_O),
    .X(_016_)
  );
  sky130_fd_sc_hd__o21ai_0 _148_ (
    .A1(SDA_O),
    .A2(_005_),
    .B1(cs[2]),
    .Y(_017_)
  );
  sky130_fd_sc_hd__o311ai_0 _149_ (
    .A1(_001_),
    .A2(_015_),
    .A3(_016_),
    .B1(_017_),
    .C1(_062_),
    .Y(_079_)
  );
  sky130_fd_sc_hd__nor2_1 _150_ (
    .A(cs[2]),
    .B(_004_),
    .Y(_018_)
  );
  sky130_fd_sc_hd__a21oi_1 _151_ (
    .A1(cs[0]),
    .A2(SCL_O),
    .B1(_037_),
    .Y(_019_)
  );
  sky130_fd_sc_hd__o22ai_1 _152_ (
    .A1(SCL_O),
    .A2(_018_),
    .B1(_019_),
    .B2(_041_),
    .Y(_080_)
  );
  sky130_fd_sc_hd__nor2_1 _153_ (
    .A(SDA_I),
    .B(receive),
    .Y(_020_)
  );
  sky130_fd_sc_hd__nand2_1 _154_ (
    .A(SCL_I),
    .B(receive),
    .Y(_021_)
  );
  sky130_fd_sc_hd__nor2_1 _155_ (
    .A(_038_),
    .B(_020_),
    .Y(_022_)
  );
  sky130_fd_sc_hd__o21ai_0 _156_ (
    .A1(_066_),
    .A2(_022_),
    .B1(_018_),
    .Y(_023_)
  );
  sky130_fd_sc_hd__nand2b_1 _157_ (
    .A_N(cs[0]),
    .B(cs[2]),
    .Y(_024_)
  );
  sky130_fd_sc_hd__a21oi_1 _158_ (
    .A1(cs[1]),
    .A2(_021_),
    .B1(_024_),
    .Y(_025_)
  );
  sky130_fd_sc_hd__nor3_1 _159_ (
    .A(SDA_I),
    .B(SCL_I),
    .C(_001_),
    .Y(_026_)
  );
  sky130_fd_sc_hd__a21oi_1 _160_ (
    .A1(start),
    .A2(_063_),
    .B1(_026_),
    .Y(_027_)
  );
  sky130_fd_sc_hd__a21oi_1 _161_ (
    .A1(_039_),
    .A2(_041_),
    .B1(_025_),
    .Y(_028_)
  );
  sky130_fd_sc_hd__nand3_1 _162_ (
    .A(_023_),
    .B(_027_),
    .C(_028_),
    .Y(ns[0])
  );
  sky130_fd_sc_hd__o21ai_0 _163_ (
    .A1(_067_),
    .A2(_022_),
    .B1(_018_),
    .Y(_029_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _164_ (
    .A(SCL_I),
    .SLEEP(SDA_I),
    .X(_030_)
  );
  sky130_fd_sc_hd__nor2_1 _165_ (
    .A(_001_),
    .B(_030_),
    .Y(_031_)
  );
  sky130_fd_sc_hd__a21oi_1 _166_ (
    .A1(done_receiving),
    .A2(_041_),
    .B1(_031_),
    .Y(_032_)
  );
  sky130_fd_sc_hd__a21o_1 _167_ (
    .A1(cs[0]),
    .A2(cs[2]),
    .B1(_006_),
    .X(_033_)
  );
  sky130_fd_sc_hd__nand3_1 _168_ (
    .A(_029_),
    .B(_032_),
    .C(_033_),
    .Y(ns[1])
  );
  sky130_fd_sc_hd__nand2_1 _169_ (
    .A(_000_),
    .B(_030_),
    .Y(_034_)
  );
  sky130_fd_sc_hd__o211ai_1 _170_ (
    .A1(_037_),
    .A2(_021_),
    .B1(_004_),
    .C1(cs[2]),
    .Y(_035_)
  );
  sky130_fd_sc_hd__nand3_1 _171_ (
    .A(_023_),
    .B(_034_),
    .C(_035_),
    .Y(ns[2])
  );
  sky130_fd_sc_hd__dfxtp_1 _172_ (
    .CLK(clk),
    .D(_072_[0]),
    .Q(received_data[0])
  );
  sky130_fd_sc_hd__dfxtp_1 _173_ (
    .CLK(clk),
    .D(_072_[1]),
    .Q(received_data[1])
  );
  sky130_fd_sc_hd__dfxtp_1 _174_ (
    .CLK(clk),
    .D(_072_[2]),
    .Q(received_data[2])
  );
  sky130_fd_sc_hd__dfxtp_1 _175_ (
    .CLK(clk),
    .D(_072_[3]),
    .Q(received_data[3])
  );
  sky130_fd_sc_hd__dfxtp_1 _176_ (
    .CLK(clk),
    .D(_072_[4]),
    .Q(received_data[4])
  );
  sky130_fd_sc_hd__dfxtp_1 _177_ (
    .CLK(clk),
    .D(_072_[5]),
    .Q(received_data[5])
  );
  sky130_fd_sc_hd__dfxtp_1 _178_ (
    .CLK(clk),
    .D(_072_[6]),
    .Q(received_data[6])
  );
  sky130_fd_sc_hd__dfxtp_1 _179_ (
    .CLK(clk),
    .D(_072_[7]),
    .Q(received_data[7])
  );
  sky130_fd_sc_hd__dfxtp_1 _180_ (
    .CLK(clk),
    .D(_080_),
    .Q(SCL_O)
  );
  sky130_fd_sc_hd__dfxtp_1 _181_ (
    .CLK(clk),
    .D(_079_),
    .Q(SDA_O)
  );
  sky130_fd_sc_hd__dfxtp_1 _182_ (
    .CLK(clk),
    .D(_078_[0]),
    .Q(counter[0])
  );
  sky130_fd_sc_hd__dfxtp_1 _183_ (
    .CLK(clk),
    .D(_078_[1]),
    .Q(counter[1])
  );
  sky130_fd_sc_hd__dfxtp_1 _184_ (
    .CLK(clk),
    .D(_078_[2]),
    .Q(counter[2])
  );
  sky130_fd_sc_hd__dfxtp_1 _185_ (
    .CLK(clk),
    .D(_077_),
    .Q(V_SCL)
  );
  sky130_fd_sc_hd__dfxtp_1 _186_ (
    .CLK(clk),
    .D(_076_),
    .Q(receive)
  );
  sky130_fd_sc_hd__dfxtp_1 _187_ (
    .CLK(clk),
    .D(_075_),
    .Q(done_receiving)
  );
  sky130_fd_sc_hd__dfxtp_1 _188_ (
    .CLK(clk),
    .D(_074_),
    .Q(begin_rec)
  );
  sky130_fd_sc_hd__dfxtp_1 _189_ (
    .CLK(clk),
    .D(_073_),
    .Q(writing)
  );
  sky130_fd_sc_hd__dfxtp_1 _190_ (
    .CLK(clk),
    .D(1'hx),
    .Q(_070_[0])
  );
  sky130_fd_sc_hd__dfxtp_1 _191_ (
    .CLK(clk),
    .D(1'hx),
    .Q(_070_[1])
  );
  sky130_fd_sc_hd__dfxtp_1 _192_ (
    .CLK(clk),
    .D(1'hx),
    .Q(_070_[2])
  );
  sky130_fd_sc_hd__dfxtp_1 _193_ (
    .CLK(clk),
    .D(1'hx),
    .Q(_071_[0])
  );
  sky130_fd_sc_hd__dfxtp_1 _194_ (
    .CLK(clk),
    .D(1'hx),
    .Q(_071_[1])
  );
  sky130_fd_sc_hd__dfxtp_1 _195_ (
    .CLK(clk),
    .D(1'hx),
    .Q(_071_[2])
  );
  sky130_fd_sc_hd__dfxtp_1 _196_ (
    .CLK(clk),
    .D(1'hx),
    .Q(_071_[3])
  );
  sky130_fd_sc_hd__dfxtp_1 _197_ (
    .CLK(clk),
    .D(1'hx),
    .Q(_071_[4])
  );
  sky130_fd_sc_hd__dfxtp_1 _198_ (
    .CLK(clk),
    .D(1'hx),
    .Q(_071_[5])
  );
  sky130_fd_sc_hd__dfxtp_1 _199_ (
    .CLK(clk),
    .D(1'hx),
    .Q(_071_[6])
  );
  sky130_fd_sc_hd__dfxtp_1 _200_ (
    .CLK(clk),
    .D(1'hx),
    .Q(_071_[7])
  );
  sky130_fd_sc_hd__dfrtp_1 _201_ (
    .CLK(clk),
    .D(ns[0]),
    .Q(cs[0]),
    .RESET_B(rst)
  );
  sky130_fd_sc_hd__dfrtp_1 _202_ (
    .CLK(clk),
    .D(ns[1]),
    .Q(cs[1]),
    .RESET_B(rst)
  );
  sky130_fd_sc_hd__dfrtp_1 _203_ (
    .CLK(clk),
    .D(ns[2]),
    .Q(cs[2]),
    .RESET_B(rst)
  );
endmodule

module I2C_Wrapper(start, Data, clk, rst, received_data);
  input [7:0] Data;
  wire [7:0] Data;
  wire SCL_M_S;
  wire SCL_S_M;
  wire SDA_M_S;
  wire SDA_S_M;
  input clk;
  wire clk;
  output [7:0] received_data;
  wire [7:0] received_data;
  input rst;
  wire rst;
  input start;
  wire start;
  I2C_Master Master (
    .Data(Data),
    .SCL_I(SCL_S_M),
    .SCL_O(SCL_M_S),
    .SDA_I(SDA_S_M),
    .SDA_O(SDA_M_S),
    .clk(clk),
    .received_data(received_data),
    .rst(rst),
    .start(start)
  );
  Memory_Slave m_slave (
    .SCL_I(SCL_M_S),
    .SCL_O(SCL_S_M),
    .SDA_I(SDA_M_S),
    .SDA_O(SDA_S_M),
    .rst(rst)
  );
endmodule

module Memory_Slave(clk, rst, vdd, gnd, SCL_I, SDA_I, SCL_O, SDA_O);
  wire [7:0] _000_;
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  wire _079_;
  wire _080_;
  wire _081_;
  wire _082_;
  wire _083_;
  wire _084_;
  wire _085_;
  wire _086_;
  wire _087_;
  wire _088_;
  wire _089_;
  wire _090_;
  wire _091_;
  wire _092_;
  wire _093_;
  wire _094_;
  wire _095_;
  wire _096_;
  wire _097_;
  wire _098_;
  wire _099_;
  wire _100_;
  wire _101_;
  wire _102_;
  wire _103_;
  wire _104_;
  wire [2:0] _105_;
  wire [2:0] _106_;
  wire [7:0] _107_;
  wire [7:0] _108_;
  wire [2:0] _109_;
  wire [7:0] _110_;
  wire [7:0] _111_;
  wire _112_;
  wire _113_;
  wire _114_;
  wire _115_;
  wire _116_;
  wire _117_;
  wire [7:0] _118_;
  wire _119_;
  wire _120_;
  input SCL_I;
  wire SCL_I;
  output SCL_O;
  wire SCL_O;
  input SDA_I;
  wire SDA_I;
  output SDA_O;
  wire SDA_O;
  wire ack_flag;
  input clk;
  wire clk;
  wire correct;
  wire [2:0] cs;
  wire done;
  input gnd;
  wire gnd;
  wire not_correct;
  wire [2:0] ns;
  input rst;
  wire rst;
  wire [7:0] slave_address;
  wire [2:0] slave_counter;
  wire [7:0] slave_data;
  wire [7:0] sram_addr;
  wire sram_csb;
  wire [7:0] sram_din;
  wire [7:0] sram_dout;
  wire sram_web;
  input vdd;
  wire vdd;
  sky130_fd_sc_hd__clkinv_1 _121_ (
    .A(SCL_I),
    .Y(_001_)
  );
  sky130_fd_sc_hd__nand2_1 _122_ (
    .A(cs[1]),
    .B(cs[0]),
    .Y(_002_)
  );
  sky130_fd_sc_hd__nand3_1 _123_ (
    .A(cs[2]),
    .B(cs[1]),
    .C(cs[0]),
    .Y(_003_)
  );
  sky130_fd_sc_hd__lpflow_inputiso1p_1 _124_ (
    .A(slave_address[0]),
    .SLEEP(_003_),
    .X(_004_)
  );
  sky130_fd_sc_hd__mux2_1 _125_ (
    .A0(slave_data[0]),
    .A1(sram_din[0]),
    .S(_004_),
    .X(_000_[0])
  );
  sky130_fd_sc_hd__nand2_1 _126_ (
    .A(sram_din[1]),
    .B(_004_),
    .Y(_005_)
  );
  sky130_fd_sc_hd__nand2b_1 _127_ (
    .A_N(slave_address[0]),
    .B(slave_data[1]),
    .Y(_006_)
  );
  sky130_fd_sc_hd__o21ai_0 _128_ (
    .A1(_003_),
    .A2(_006_),
    .B1(_005_),
    .Y(_000_[1])
  );
  sky130_fd_sc_hd__nand2_1 _129_ (
    .A(sram_din[2]),
    .B(_004_),
    .Y(_007_)
  );
  sky130_fd_sc_hd__nand2b_1 _130_ (
    .A_N(slave_address[0]),
    .B(slave_data[2]),
    .Y(_008_)
  );
  sky130_fd_sc_hd__o21ai_0 _131_ (
    .A1(_003_),
    .A2(_008_),
    .B1(_007_),
    .Y(_000_[2])
  );
  sky130_fd_sc_hd__nand2_1 _132_ (
    .A(sram_din[3]),
    .B(_004_),
    .Y(_009_)
  );
  sky130_fd_sc_hd__nand2b_1 _133_ (
    .A_N(slave_address[0]),
    .B(slave_data[3]),
    .Y(_010_)
  );
  sky130_fd_sc_hd__o21ai_0 _134_ (
    .A1(_003_),
    .A2(_010_),
    .B1(_009_),
    .Y(_000_[3])
  );
  sky130_fd_sc_hd__mux2_1 _135_ (
    .A0(slave_data[4]),
    .A1(sram_din[4]),
    .S(_004_),
    .X(_000_[4])
  );
  sky130_fd_sc_hd__mux2_1 _136_ (
    .A0(slave_data[5]),
    .A1(sram_din[5]),
    .S(_004_),
    .X(_000_[5])
  );
  sky130_fd_sc_hd__mux2_1 _137_ (
    .A0(slave_data[6]),
    .A1(sram_din[6]),
    .S(_004_),
    .X(_000_[6])
  );
  sky130_fd_sc_hd__mux2_1 _138_ (
    .A0(slave_data[7]),
    .A1(sram_din[7]),
    .S(_004_),
    .X(_000_[7])
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _139_ (
    .A(cs[1]),
    .SLEEP(cs[0]),
    .X(_011_)
  );
  sky130_fd_sc_hd__nor3b_1 _140_ (
    .A(cs[2]),
    .B(cs[0]),
    .C_N(cs[1]),
    .Y(_012_)
  );
  sky130_fd_sc_hd__nand2b_1 _141_ (
    .A_N(cs[2]),
    .B(_011_),
    .Y(_013_)
  );
  sky130_fd_sc_hd__nor2_1 _142_ (
    .A(cs[1]),
    .B(cs[0]),
    .Y(_014_)
  );
  sky130_fd_sc_hd__or3_1 _143_ (
    .A(cs[2]),
    .B(cs[1]),
    .C(cs[0]),
    .X(_015_)
  );
  sky130_fd_sc_hd__nor2_1 _144_ (
    .A(cs[2]),
    .B(cs[0]),
    .Y(_016_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _145_ (
    .A(cs[0]),
    .SLEEP(cs[1]),
    .X(_017_)
  );
  sky130_fd_sc_hd__nand2b_1 _146_ (
    .A_N(cs[1]),
    .B(cs[0]),
    .Y(_018_)
  );
  sky130_fd_sc_hd__and2_0 _147_ (
    .A(cs[2]),
    .B(_011_),
    .X(_019_)
  );
  sky130_fd_sc_hd__nand3b_1 _148_ (
    .A_N(cs[0]),
    .B(cs[1]),
    .C(cs[2]),
    .Y(_020_)
  );
  sky130_fd_sc_hd__nor2_1 _149_ (
    .A(cs[2]),
    .B(_018_),
    .Y(_021_)
  );
  sky130_fd_sc_hd__or3b_1 _150_ (
    .A(cs[2]),
    .B(cs[1]),
    .C_N(cs[0]),
    .X(_022_)
  );
  sky130_fd_sc_hd__nand2_1 _151_ (
    .A(cs[2]),
    .B(_017_),
    .Y(_023_)
  );
  sky130_fd_sc_hd__o21ai_0 _152_ (
    .A1(_011_),
    .A2(_017_),
    .B1(cs[2]),
    .Y(_024_)
  );
  sky130_fd_sc_hd__nor2_1 _153_ (
    .A(slave_counter[0]),
    .B(slave_counter[1]),
    .Y(_025_)
  );
  sky130_fd_sc_hd__nor3_1 _154_ (
    .A(slave_counter[0]),
    .B(slave_counter[1]),
    .C(slave_counter[2]),
    .Y(_026_)
  );
  sky130_fd_sc_hd__a22oi_1 _155_ (
    .A1(_018_),
    .A2(_020_),
    .B1(_022_),
    .B2(_026_),
    .Y(_027_)
  );
  sky130_fd_sc_hd__or3b_1 _156_ (
    .A(cs[1]),
    .B(cs[0]),
    .C_N(cs[2]),
    .X(_028_)
  );
  sky130_fd_sc_hd__nand2_1 _157_ (
    .A(_002_),
    .B(_028_),
    .Y(_029_)
  );
  sky130_fd_sc_hd__nand3_1 _158_ (
    .A(slave_counter[0]),
    .B(_002_),
    .C(_028_),
    .Y(_030_)
  );
  sky130_fd_sc_hd__o21ai_0 _159_ (
    .A1(slave_counter[0]),
    .A2(_027_),
    .B1(_030_),
    .Y(_031_)
  );
  sky130_fd_sc_hd__o21ai_0 _160_ (
    .A1(cs[2]),
    .A2(cs[0]),
    .B1(_031_),
    .Y(_109_[0])
  );
  sky130_fd_sc_hd__nand2_1 _161_ (
    .A(slave_counter[0]),
    .B(slave_counter[1]),
    .Y(_032_)
  );
  sky130_fd_sc_hd__nand2b_1 _162_ (
    .A_N(_025_),
    .B(_032_),
    .Y(_033_)
  );
  sky130_fd_sc_hd__a221o_1 _163_ (
    .A1(slave_counter[1]),
    .A2(_029_),
    .B1(_033_),
    .B2(_027_),
    .C1(_016_),
    .X(_109_[1])
  );
  sky130_fd_sc_hd__a21oi_1 _164_ (
    .A1(_018_),
    .A2(_020_),
    .B1(_025_),
    .Y(_034_)
  );
  sky130_fd_sc_hd__o21ai_0 _165_ (
    .A1(_029_),
    .A2(_034_),
    .B1(slave_counter[2]),
    .Y(_035_)
  );
  sky130_fd_sc_hd__nand2_1 _166_ (
    .A(_021_),
    .B(_026_),
    .Y(_036_)
  );
  sky130_fd_sc_hd__nand4_1 _167_ (
    .A(_013_),
    .B(_015_),
    .C(_035_),
    .D(_036_),
    .Y(_109_[2])
  );
  sky130_fd_sc_hd__o21ai_0 _168_ (
    .A1(cs[2]),
    .A2(slave_address[0]),
    .B1(_011_),
    .Y(_037_)
  );
  sky130_fd_sc_hd__and2_0 _169_ (
    .A(slave_address[0]),
    .B(_012_),
    .X(_038_)
  );
  sky130_fd_sc_hd__nand2_1 _170_ (
    .A(SDA_I),
    .B(_026_),
    .Y(_039_)
  );
  sky130_fd_sc_hd__nand2b_1 _171_ (
    .A_N(_026_),
    .B(slave_data[0]),
    .Y(_040_)
  );
  sky130_fd_sc_hd__a21oi_1 _172_ (
    .A1(_039_),
    .A2(_040_),
    .B1(_020_),
    .Y(_041_)
  );
  sky130_fd_sc_hd__a221o_1 _173_ (
    .A1(slave_data[0]),
    .A2(_037_),
    .B1(_038_),
    .B2(sram_dout[0]),
    .C1(_041_),
    .X(_110_[0])
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _174_ (
    .A(slave_counter[0]),
    .SLEEP(slave_counter[1]),
    .X(_042_)
  );
  sky130_fd_sc_hd__nor3b_1 _175_ (
    .A(slave_counter[1]),
    .B(slave_counter[2]),
    .C_N(slave_counter[0]),
    .Y(_043_)
  );
  sky130_fd_sc_hd__nand2_1 _176_ (
    .A(SDA_I),
    .B(_043_),
    .Y(_044_)
  );
  sky130_fd_sc_hd__a32oi_1 _177_ (
    .A1(SDA_I),
    .A2(_019_),
    .A3(_043_),
    .B1(_038_),
    .B2(sram_dout[1]),
    .Y(_045_)
  );
  sky130_fd_sc_hd__nand2_1 _178_ (
    .A(_011_),
    .B(_043_),
    .Y(_046_)
  );
  sky130_fd_sc_hd__nand3_1 _179_ (
    .A(slave_data[1]),
    .B(_013_),
    .C(_046_),
    .Y(_047_)
  );
  sky130_fd_sc_hd__o211ai_1 _180_ (
    .A1(_006_),
    .A2(_013_),
    .B1(_045_),
    .C1(_047_),
    .Y(_110_[1])
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _181_ (
    .A(slave_counter[1]),
    .SLEEP(slave_counter[0]),
    .X(_048_)
  );
  sky130_fd_sc_hd__nor3b_1 _182_ (
    .A(slave_counter[0]),
    .B(slave_counter[2]),
    .C_N(slave_counter[1]),
    .Y(_049_)
  );
  sky130_fd_sc_hd__nand2_1 _183_ (
    .A(SDA_I),
    .B(_049_),
    .Y(_050_)
  );
  sky130_fd_sc_hd__a32oi_1 _184_ (
    .A1(SDA_I),
    .A2(_019_),
    .A3(_049_),
    .B1(_038_),
    .B2(sram_dout[2]),
    .Y(_051_)
  );
  sky130_fd_sc_hd__nand2_1 _185_ (
    .A(_011_),
    .B(_049_),
    .Y(_052_)
  );
  sky130_fd_sc_hd__nand3_1 _186_ (
    .A(slave_data[2]),
    .B(_013_),
    .C(_052_),
    .Y(_053_)
  );
  sky130_fd_sc_hd__o211ai_1 _187_ (
    .A1(_008_),
    .A2(_013_),
    .B1(_051_),
    .C1(_053_),
    .Y(_110_[2])
  );
  sky130_fd_sc_hd__nand4b_1 _188_ (
    .A_N(slave_counter[2]),
    .B(SDA_I),
    .C(slave_counter[0]),
    .D(slave_counter[1]),
    .Y(_054_)
  );
  sky130_fd_sc_hd__nor2_1 _189_ (
    .A(_020_),
    .B(_054_),
    .Y(_055_)
  );
  sky130_fd_sc_hd__a21oi_1 _190_ (
    .A1(sram_dout[3]),
    .A2(_038_),
    .B1(_055_),
    .Y(_056_)
  );
  sky130_fd_sc_hd__or3b_1 _191_ (
    .A(_032_),
    .B(slave_counter[2]),
    .C_N(_011_),
    .X(_057_)
  );
  sky130_fd_sc_hd__nand3_1 _192_ (
    .A(slave_data[3]),
    .B(_013_),
    .C(_057_),
    .Y(_058_)
  );
  sky130_fd_sc_hd__o211ai_1 _193_ (
    .A1(_010_),
    .A2(_013_),
    .B1(_056_),
    .C1(_058_),
    .Y(_110_[3])
  );
  sky130_fd_sc_hd__or3b_1 _194_ (
    .A(slave_counter[0]),
    .B(slave_counter[1]),
    .C_N(slave_counter[2]),
    .X(_059_)
  );
  sky130_fd_sc_hd__nand3_1 _195_ (
    .A(slave_counter[2]),
    .B(SDA_I),
    .C(_025_),
    .Y(_060_)
  );
  sky130_fd_sc_hd__nand2_1 _196_ (
    .A(slave_data[4]),
    .B(_059_),
    .Y(_061_)
  );
  sky130_fd_sc_hd__a21oi_1 _197_ (
    .A1(_060_),
    .A2(_061_),
    .B1(_020_),
    .Y(_062_)
  );
  sky130_fd_sc_hd__a221o_1 _198_ (
    .A1(slave_data[4]),
    .A2(_037_),
    .B1(_038_),
    .B2(sram_dout[4]),
    .C1(_062_),
    .X(_110_[4])
  );
  sky130_fd_sc_hd__nand3b_1 _199_ (
    .A_N(slave_counter[1]),
    .B(slave_counter[2]),
    .C(slave_counter[0]),
    .Y(_063_)
  );
  sky130_fd_sc_hd__nand3_1 _200_ (
    .A(slave_counter[2]),
    .B(SDA_I),
    .C(_042_),
    .Y(_064_)
  );
  sky130_fd_sc_hd__nand2_1 _201_ (
    .A(slave_data[5]),
    .B(_063_),
    .Y(_065_)
  );
  sky130_fd_sc_hd__a21oi_1 _202_ (
    .A1(_064_),
    .A2(_065_),
    .B1(_020_),
    .Y(_066_)
  );
  sky130_fd_sc_hd__a221o_1 _203_ (
    .A1(slave_data[5]),
    .A2(_037_),
    .B1(_038_),
    .B2(sram_dout[5]),
    .C1(_066_),
    .X(_110_[5])
  );
  sky130_fd_sc_hd__nand3b_1 _204_ (
    .A_N(slave_counter[0]),
    .B(slave_counter[1]),
    .C(slave_counter[2]),
    .Y(_067_)
  );
  sky130_fd_sc_hd__nand3_1 _205_ (
    .A(slave_counter[2]),
    .B(SDA_I),
    .C(_048_),
    .Y(_068_)
  );
  sky130_fd_sc_hd__nand2_1 _206_ (
    .A(slave_data[6]),
    .B(_067_),
    .Y(_069_)
  );
  sky130_fd_sc_hd__a21oi_1 _207_ (
    .A1(_068_),
    .A2(_069_),
    .B1(_020_),
    .Y(_070_)
  );
  sky130_fd_sc_hd__a221o_1 _208_ (
    .A1(slave_data[6]),
    .A2(_037_),
    .B1(_038_),
    .B2(sram_dout[6]),
    .C1(_070_),
    .X(_110_[6])
  );
  sky130_fd_sc_hd__nand3_1 _209_ (
    .A(slave_counter[0]),
    .B(slave_counter[1]),
    .C(slave_counter[2]),
    .Y(_071_)
  );
  sky130_fd_sc_hd__nand4_1 _210_ (
    .A(slave_counter[0]),
    .B(slave_counter[1]),
    .C(slave_counter[2]),
    .D(SDA_I),
    .Y(_072_)
  );
  sky130_fd_sc_hd__nand2_1 _211_ (
    .A(slave_data[7]),
    .B(_071_),
    .Y(_073_)
  );
  sky130_fd_sc_hd__a21oi_1 _212_ (
    .A1(_072_),
    .A2(_073_),
    .B1(_020_),
    .Y(_074_)
  );
  sky130_fd_sc_hd__a221o_1 _213_ (
    .A1(slave_data[7]),
    .A2(_037_),
    .B1(_038_),
    .B2(sram_dout[7]),
    .C1(_074_),
    .X(_110_[7])
  );
  sky130_fd_sc_hd__o2bb2ai_1 _214_ (
    .A1_N(slave_address[0]),
    .A2_N(_036_),
    .B1(_039_),
    .B2(_022_),
    .Y(_111_[0])
  );
  sky130_fd_sc_hd__nand2_1 _215_ (
    .A(_021_),
    .B(_043_),
    .Y(_075_)
  );
  sky130_fd_sc_hd__o2bb2ai_1 _216_ (
    .A1_N(slave_address[1]),
    .A2_N(_075_),
    .B1(_044_),
    .B2(_022_),
    .Y(_111_[1])
  );
  sky130_fd_sc_hd__nand2_1 _217_ (
    .A(_021_),
    .B(_049_),
    .Y(_076_)
  );
  sky130_fd_sc_hd__o2bb2ai_1 _218_ (
    .A1_N(slave_address[2]),
    .A2_N(_076_),
    .B1(_050_),
    .B2(_022_),
    .Y(_111_[2])
  );
  sky130_fd_sc_hd__o31ai_1 _219_ (
    .A1(slave_counter[2]),
    .A2(_022_),
    .A3(_032_),
    .B1(slave_address[3]),
    .Y(_077_)
  );
  sky130_fd_sc_hd__o21ai_0 _220_ (
    .A1(_022_),
    .A2(_054_),
    .B1(_077_),
    .Y(_111_[3])
  );
  sky130_fd_sc_hd__o21ai_0 _221_ (
    .A1(_022_),
    .A2(_059_),
    .B1(slave_address[4]),
    .Y(_078_)
  );
  sky130_fd_sc_hd__o21ai_0 _222_ (
    .A1(_022_),
    .A2(_060_),
    .B1(_078_),
    .Y(_111_[4])
  );
  sky130_fd_sc_hd__o21ai_0 _223_ (
    .A1(_022_),
    .A2(_063_),
    .B1(slave_address[5]),
    .Y(_079_)
  );
  sky130_fd_sc_hd__o21ai_0 _224_ (
    .A1(_022_),
    .A2(_064_),
    .B1(_079_),
    .Y(_111_[5])
  );
  sky130_fd_sc_hd__o21ai_0 _225_ (
    .A1(_022_),
    .A2(_067_),
    .B1(slave_address[6]),
    .Y(_080_)
  );
  sky130_fd_sc_hd__o21ai_0 _226_ (
    .A1(_022_),
    .A2(_068_),
    .B1(_080_),
    .Y(_111_[6])
  );
  sky130_fd_sc_hd__o21ai_0 _227_ (
    .A1(_022_),
    .A2(_071_),
    .B1(slave_address[7]),
    .Y(_081_)
  );
  sky130_fd_sc_hd__o21ai_0 _228_ (
    .A1(_022_),
    .A2(_072_),
    .B1(_081_),
    .Y(_111_[7])
  );
  sky130_fd_sc_hd__nand2_1 _229_ (
    .A(done),
    .B(_015_),
    .Y(_082_)
  );
  sky130_fd_sc_hd__o41ai_1 _230_ (
    .A1(slave_counter[0]),
    .A2(slave_counter[1]),
    .A3(slave_counter[2]),
    .A4(_024_),
    .B1(_082_),
    .Y(_112_)
  );
  sky130_fd_sc_hd__nand4_1 _231_ (
    .A(slave_address[1]),
    .B(slave_address[2]),
    .C(slave_address[3]),
    .D(slave_address[4]),
    .Y(_083_)
  );
  sky130_fd_sc_hd__nor4b_1 _232_ (
    .A(slave_address[6]),
    .B(slave_address[7]),
    .C(_083_),
    .D_N(slave_address[5]),
    .Y(_084_)
  );
  sky130_fd_sc_hd__lpflow_inputiso1p_1 _233_ (
    .A(cs[2]),
    .SLEEP(_017_),
    .X(_085_)
  );
  sky130_fd_sc_hd__o2bb2ai_1 _234_ (
    .A1_N(not_correct),
    .A2_N(_085_),
    .B1(_036_),
    .B2(_084_),
    .Y(_113_)
  );
  sky130_fd_sc_hd__a32o_1 _235_ (
    .A1(_021_),
    .A2(_026_),
    .A3(_084_),
    .B1(_085_),
    .B2(correct),
    .X(_114_)
  );
  sky130_fd_sc_hd__nand2_1 _236_ (
    .A(ack_flag),
    .B(_015_),
    .Y(_086_)
  );
  sky130_fd_sc_hd__nand2_1 _237_ (
    .A(_013_),
    .B(_086_),
    .Y(_115_)
  );
  sky130_fd_sc_hd__o21ai_0 _238_ (
    .A1(sram_web),
    .A2(_038_),
    .B1(_004_),
    .Y(_087_)
  );
  sky130_fd_sc_hd__nand2_1 _239_ (
    .A(_015_),
    .B(_087_),
    .Y(_116_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _240_ (
    .A(_004_),
    .SLEEP(_038_),
    .X(_088_)
  );
  sky130_fd_sc_hd__a21bo_1 _241_ (
    .A1(sram_csb),
    .A2(_088_),
    .B1_N(_015_),
    .X(_117_)
  );
  sky130_fd_sc_hd__mux2_1 _242_ (
    .A0(slave_address[1]),
    .A1(sram_addr[0]),
    .S(_088_),
    .X(_118_[0])
  );
  sky130_fd_sc_hd__mux2_1 _243_ (
    .A0(slave_address[2]),
    .A1(sram_addr[1]),
    .S(_088_),
    .X(_118_[1])
  );
  sky130_fd_sc_hd__mux2_1 _244_ (
    .A0(slave_address[3]),
    .A1(sram_addr[2]),
    .S(_088_),
    .X(_118_[2])
  );
  sky130_fd_sc_hd__mux2_1 _245_ (
    .A0(slave_address[4]),
    .A1(sram_addr[3]),
    .S(_088_),
    .X(_118_[3])
  );
  sky130_fd_sc_hd__mux2_1 _246_ (
    .A0(slave_address[5]),
    .A1(sram_addr[4]),
    .S(_088_),
    .X(_118_[4])
  );
  sky130_fd_sc_hd__mux2_1 _247_ (
    .A0(slave_address[6]),
    .A1(sram_addr[5]),
    .S(_088_),
    .X(_118_[5])
  );
  sky130_fd_sc_hd__mux2_1 _248_ (
    .A0(slave_address[7]),
    .A1(sram_addr[6]),
    .S(_088_),
    .X(_118_[6])
  );
  sky130_fd_sc_hd__and2_0 _249_ (
    .A(sram_addr[7]),
    .B(_088_),
    .X(_118_[7])
  );
  sky130_fd_sc_hd__a221o_1 _250_ (
    .A1(cs[2]),
    .A2(cs[1]),
    .B1(SDA_O),
    .B2(_021_),
    .C1(_014_),
    .X(_089_)
  );
  sky130_fd_sc_hd__a31oi_1 _251_ (
    .A1(slave_counter[0]),
    .A2(slave_counter[1]),
    .A3(slave_data[3]),
    .B1(slave_counter[2]),
    .Y(_090_)
  );
  sky130_fd_sc_hd__a222oi_1 _252_ (
    .A1(slave_data[0]),
    .A2(_025_),
    .B1(_042_),
    .B2(slave_data[1]),
    .C1(_048_),
    .C2(slave_data[2]),
    .Y(_091_)
  );
  sky130_fd_sc_hd__nand2_1 _253_ (
    .A(slave_data[4]),
    .B(_025_),
    .Y(_092_)
  );
  sky130_fd_sc_hd__and3_1 _254_ (
    .A(slave_counter[0]),
    .B(slave_counter[1]),
    .C(slave_data[7]),
    .X(_093_)
  );
  sky130_fd_sc_hd__a221oi_1 _255_ (
    .A1(slave_data[5]),
    .A2(_042_),
    .B1(_048_),
    .B2(slave_data[6]),
    .C1(_093_),
    .Y(_094_)
  );
  sky130_fd_sc_hd__nand3_1 _256_ (
    .A(slave_counter[2]),
    .B(_092_),
    .C(_094_),
    .Y(_095_)
  );
  sky130_fd_sc_hd__a21oi_1 _257_ (
    .A1(_090_),
    .A2(_091_),
    .B1(_023_),
    .Y(_096_)
  );
  sky130_fd_sc_hd__a21o_1 _258_ (
    .A1(_095_),
    .A2(_096_),
    .B1(_089_),
    .X(_119_)
  );
  sky130_fd_sc_hd__nand2b_1 _259_ (
    .A_N(cs[2]),
    .B(SCL_O),
    .Y(_097_)
  );
  sky130_fd_sc_hd__o21ai_0 _260_ (
    .A1(_014_),
    .A2(_097_),
    .B1(_002_),
    .Y(_120_)
  );
  sky130_fd_sc_hd__o22ai_1 _261_ (
    .A1(SDA_I),
    .A2(_015_),
    .B1(_023_),
    .B2(done),
    .Y(_098_)
  );
  sky130_fd_sc_hd__nand3_1 _262_ (
    .A(cs[2]),
    .B(slave_address[0]),
    .C(_014_),
    .Y(_099_)
  );
  sky130_fd_sc_hd__o21ai_0 _263_ (
    .A1(correct),
    .A2(_022_),
    .B1(_099_),
    .Y(_100_)
  );
  sky130_fd_sc_hd__a211o_1 _264_ (
    .A1(ack_flag),
    .A2(_012_),
    .B1(_098_),
    .C1(_100_),
    .X(ns[0])
  );
  sky130_fd_sc_hd__o21ai_0 _265_ (
    .A1(cs[2]),
    .A2(ack_flag),
    .B1(_011_),
    .Y(_101_)
  );
  sky130_fd_sc_hd__nor2_1 _266_ (
    .A(correct),
    .B(not_correct),
    .Y(_102_)
  );
  sky130_fd_sc_hd__nor2_1 _267_ (
    .A(_022_),
    .B(_102_),
    .Y(_103_)
  );
  sky130_fd_sc_hd__a31oi_1 _268_ (
    .A1(cs[2]),
    .A2(done),
    .A3(_017_),
    .B1(_103_),
    .Y(_104_)
  );
  sky130_fd_sc_hd__o211ai_1 _269_ (
    .A1(slave_address[0]),
    .A2(_028_),
    .B1(_101_),
    .C1(_104_),
    .Y(ns[1])
  );
  sky130_fd_sc_hd__o211ai_1 _270_ (
    .A1(done),
    .A2(_024_),
    .B1(_028_),
    .C1(_013_),
    .Y(ns[2])
  );
  sky130_fd_sc_hd__dfxtp_1 _271_ (
    .CLK(_001_),
    .D(_120_),
    .Q(SCL_O)
  );
  sky130_fd_sc_hd__dfxtp_1 _272_ (
    .CLK(_001_),
    .D(_119_),
    .Q(SDA_O)
  );
  sky130_fd_sc_hd__dfxtp_1 _273_ (
    .CLK(_001_),
    .D(_000_[0]),
    .Q(sram_din[0])
  );
  sky130_fd_sc_hd__dfxtp_1 _274_ (
    .CLK(_001_),
    .D(_000_[1]),
    .Q(sram_din[1])
  );
  sky130_fd_sc_hd__dfxtp_1 _275_ (
    .CLK(_001_),
    .D(_000_[2]),
    .Q(sram_din[2])
  );
  sky130_fd_sc_hd__dfxtp_1 _276_ (
    .CLK(_001_),
    .D(_000_[3]),
    .Q(sram_din[3])
  );
  sky130_fd_sc_hd__dfxtp_1 _277_ (
    .CLK(_001_),
    .D(_000_[4]),
    .Q(sram_din[4])
  );
  sky130_fd_sc_hd__dfxtp_1 _278_ (
    .CLK(_001_),
    .D(_000_[5]),
    .Q(sram_din[5])
  );
  sky130_fd_sc_hd__dfxtp_1 _279_ (
    .CLK(_001_),
    .D(_000_[6]),
    .Q(sram_din[6])
  );
  sky130_fd_sc_hd__dfxtp_1 _280_ (
    .CLK(_001_),
    .D(_000_[7]),
    .Q(sram_din[7])
  );
  sky130_fd_sc_hd__dfxtp_1 _281_ (
    .CLK(_001_),
    .D(_118_[0]),
    .Q(sram_addr[0])
  );
  sky130_fd_sc_hd__dfxtp_1 _282_ (
    .CLK(_001_),
    .D(_118_[1]),
    .Q(sram_addr[1])
  );
  sky130_fd_sc_hd__dfxtp_1 _283_ (
    .CLK(_001_),
    .D(_118_[2]),
    .Q(sram_addr[2])
  );
  sky130_fd_sc_hd__dfxtp_1 _284_ (
    .CLK(_001_),
    .D(_118_[3]),
    .Q(sram_addr[3])
  );
  sky130_fd_sc_hd__dfxtp_1 _285_ (
    .CLK(_001_),
    .D(_118_[4]),
    .Q(sram_addr[4])
  );
  sky130_fd_sc_hd__dfxtp_1 _286_ (
    .CLK(_001_),
    .D(_118_[5]),
    .Q(sram_addr[5])
  );
  sky130_fd_sc_hd__dfxtp_1 _287_ (
    .CLK(_001_),
    .D(_118_[6]),
    .Q(sram_addr[6])
  );
  sky130_fd_sc_hd__dfxtp_1 _288_ (
    .CLK(_001_),
    .D(_118_[7]),
    .Q(sram_addr[7])
  );
  sky130_fd_sc_hd__dfxtp_1 _289_ (
    .CLK(_001_),
    .D(_117_),
    .Q(sram_csb)
  );
  sky130_fd_sc_hd__dfxtp_1 _290_ (
    .CLK(_001_),
    .D(_116_),
    .Q(sram_web)
  );
  sky130_fd_sc_hd__dfxtp_1 _291_ (
    .CLK(_001_),
    .D(_109_[0]),
    .Q(slave_counter[0])
  );
  sky130_fd_sc_hd__dfxtp_1 _292_ (
    .CLK(_001_),
    .D(_109_[1]),
    .Q(slave_counter[1])
  );
  sky130_fd_sc_hd__dfxtp_1 _293_ (
    .CLK(_001_),
    .D(_109_[2]),
    .Q(slave_counter[2])
  );
  sky130_fd_sc_hd__dfxtp_1 _294_ (
    .CLK(_001_),
    .D(_115_),
    .Q(ack_flag)
  );
  sky130_fd_sc_hd__dfxtp_1 _295_ (
    .CLK(_001_),
    .D(_114_),
    .Q(correct)
  );
  sky130_fd_sc_hd__dfxtp_1 _296_ (
    .CLK(_001_),
    .D(_113_),
    .Q(not_correct)
  );
  sky130_fd_sc_hd__dfxtp_1 _297_ (
    .CLK(_001_),
    .D(_112_),
    .Q(done)
  );
  sky130_fd_sc_hd__dfxtp_1 _298_ (
    .CLK(_001_),
    .D(_111_[0]),
    .Q(slave_address[0])
  );
  sky130_fd_sc_hd__dfxtp_1 _299_ (
    .CLK(_001_),
    .D(_111_[1]),
    .Q(slave_address[1])
  );
  sky130_fd_sc_hd__dfxtp_1 _300_ (
    .CLK(_001_),
    .D(_111_[2]),
    .Q(slave_address[2])
  );
  sky130_fd_sc_hd__dfxtp_1 _301_ (
    .CLK(_001_),
    .D(_111_[3]),
    .Q(slave_address[3])
  );
  sky130_fd_sc_hd__dfxtp_1 _302_ (
    .CLK(_001_),
    .D(_111_[4]),
    .Q(slave_address[4])
  );
  sky130_fd_sc_hd__dfxtp_1 _303_ (
    .CLK(_001_),
    .D(_111_[5]),
    .Q(slave_address[5])
  );
  sky130_fd_sc_hd__dfxtp_1 _304_ (
    .CLK(_001_),
    .D(_111_[6]),
    .Q(slave_address[6])
  );
  sky130_fd_sc_hd__dfxtp_1 _305_ (
    .CLK(_001_),
    .D(_111_[7]),
    .Q(slave_address[7])
  );
  sky130_fd_sc_hd__dfxtp_1 _306_ (
    .CLK(_001_),
    .D(_110_[0]),
    .Q(slave_data[0])
  );
  sky130_fd_sc_hd__dfxtp_1 _307_ (
    .CLK(_001_),
    .D(_110_[1]),
    .Q(slave_data[1])
  );
  sky130_fd_sc_hd__dfxtp_1 _308_ (
    .CLK(_001_),
    .D(_110_[2]),
    .Q(slave_data[2])
  );
  sky130_fd_sc_hd__dfxtp_1 _309_ (
    .CLK(_001_),
    .D(_110_[3]),
    .Q(slave_data[3])
  );
  sky130_fd_sc_hd__dfxtp_1 _310_ (
    .CLK(_001_),
    .D(_110_[4]),
    .Q(slave_data[4])
  );
  sky130_fd_sc_hd__dfxtp_1 _311_ (
    .CLK(_001_),
    .D(_110_[5]),
    .Q(slave_data[5])
  );
  sky130_fd_sc_hd__dfxtp_1 _312_ (
    .CLK(_001_),
    .D(_110_[6]),
    .Q(slave_data[6])
  );
  sky130_fd_sc_hd__dfxtp_1 _313_ (
    .CLK(_001_),
    .D(_110_[7]),
    .Q(slave_data[7])
  );
  sky130_fd_sc_hd__dfxtp_1 _314_ (
    .CLK(_001_),
    .D(1'hx),
    .Q(_106_[0])
  );
  sky130_fd_sc_hd__dfxtp_1 _315_ (
    .CLK(_001_),
    .D(1'hx),
    .Q(_106_[1])
  );
  sky130_fd_sc_hd__dfxtp_1 _316_ (
    .CLK(_001_),
    .D(1'hx),
    .Q(_106_[2])
  );
  sky130_fd_sc_hd__dfxtp_1 _317_ (
    .CLK(_001_),
    .D(1'hx),
    .Q(_105_[0])
  );
  sky130_fd_sc_hd__dfxtp_1 _318_ (
    .CLK(_001_),
    .D(1'hx),
    .Q(_105_[1])
  );
  sky130_fd_sc_hd__dfxtp_1 _319_ (
    .CLK(_001_),
    .D(1'hx),
    .Q(_105_[2])
  );
  sky130_fd_sc_hd__dfxtp_1 _320_ (
    .CLK(_001_),
    .D(1'hx),
    .Q(_107_[0])
  );
  sky130_fd_sc_hd__dfxtp_1 _321_ (
    .CLK(_001_),
    .D(1'hx),
    .Q(_107_[1])
  );
  sky130_fd_sc_hd__dfxtp_1 _322_ (
    .CLK(_001_),
    .D(1'hx),
    .Q(_107_[2])
  );
  sky130_fd_sc_hd__dfxtp_1 _323_ (
    .CLK(_001_),
    .D(1'hx),
    .Q(_107_[3])
  );
  sky130_fd_sc_hd__dfxtp_1 _324_ (
    .CLK(_001_),
    .D(1'hx),
    .Q(_107_[4])
  );
  sky130_fd_sc_hd__dfxtp_1 _325_ (
    .CLK(_001_),
    .D(1'hx),
    .Q(_107_[5])
  );
  sky130_fd_sc_hd__dfxtp_1 _326_ (
    .CLK(_001_),
    .D(1'hx),
    .Q(_107_[6])
  );
  sky130_fd_sc_hd__dfxtp_1 _327_ (
    .CLK(_001_),
    .D(1'hx),
    .Q(_107_[7])
  );
  sky130_fd_sc_hd__dfxtp_1 _328_ (
    .CLK(_001_),
    .D(1'hx),
    .Q(_108_[0])
  );
  sky130_fd_sc_hd__dfxtp_1 _329_ (
    .CLK(_001_),
    .D(1'hx),
    .Q(_108_[1])
  );
  sky130_fd_sc_hd__dfxtp_1 _330_ (
    .CLK(_001_),
    .D(1'hx),
    .Q(_108_[2])
  );
  sky130_fd_sc_hd__dfxtp_1 _331_ (
    .CLK(_001_),
    .D(1'hx),
    .Q(_108_[3])
  );
  sky130_fd_sc_hd__dfxtp_1 _332_ (
    .CLK(_001_),
    .D(1'hx),
    .Q(_108_[4])
  );
  sky130_fd_sc_hd__dfxtp_1 _333_ (
    .CLK(_001_),
    .D(1'hx),
    .Q(_108_[5])
  );
  sky130_fd_sc_hd__dfxtp_1 _334_ (
    .CLK(_001_),
    .D(1'hx),
    .Q(_108_[6])
  );
  sky130_fd_sc_hd__dfxtp_1 _335_ (
    .CLK(_001_),
    .D(1'hx),
    .Q(_108_[7])
  );
  sky130_fd_sc_hd__dfrtn_1 _336_ (
    .CLK_N(SCL_I),
    .D(ns[0]),
    .Q(cs[0]),
    .RESET_B(rst)
  );
  sky130_fd_sc_hd__dfrtn_1 _337_ (
    .CLK_N(SCL_I),
    .D(ns[1]),
    .Q(cs[1]),
    .RESET_B(rst)
  );
  sky130_fd_sc_hd__dfrtn_1 _338_ (
    .CLK_N(SCL_I),
    .D(ns[2]),
    .Q(cs[2]),
    .RESET_B(rst)
  );
  sram_8_256_sky130A SRAM (
    .addr0(sram_addr),
    .clk0(clk),
    .csb0(sram_csb),
    .din0(sram_din),
    .dout0(sram_dout),
    .gnd(gnd),
    .vdd(vdd),
    .web0(sram_web)
  );
endmodule
